version: '2.1'

services:
  spark-master:
    image: elastest/ebs:0.1
    container_name: spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./spark/alluxio_conf:/opt/alluxio/conf
      - ./spark/spark_conf:/opt/spark/conf
      - ./spark/hadoop_conf:/usr/local/hadoop/etc/hadoop
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]
    hostname: spark-master
    networks:
      - elastest

  spark-worker:
    image: elastest/ebs:0.1
    depends_on:
      - spark-master
    ports:
      - "8081"
    volumes:
      - ./spark/alluxio_conf:/opt/alluxio/conf
      - ./spark/spark_conf:/opt/spark/conf
      - ./spark/hadoop_conf:/usr/local/hadoop/etc/hadoop
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]
    networks:
      - elastest

  rest-api:
    build: ./rest-api  # path is relative to docker-compose.yml location
    # image: elastest/edm:0.1
    environment:
      - EBS_PORT=5000
    volumes:
      - ./rest-api:/app # mount point
    links:
      - spark-master
    ports:
      - 5000:5000  # host:container
    networks:
        - elastest

networks:
  elastest:
    external: true
